name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  rust:
    name: Lint and Test
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, blacksmith-staging, blacksmith, blacksmith-4vcpu-ubuntu-2204]

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy

      - name: Use blacksmith rust cache
        if: matrix.platform != 'ubuntu-latest'
        uses: useblacksmith/rust-cache@v3

      - name: Use ubuntu rust cache
        if: matrix.platform == 'ubuntu-latest'
        uses: Swatinem/rust-cache@v2

      - run: cargo build --all-features

      - run: cargo test

      - run: cargo clippy -- -D warnings

  rustfmt:
    name: Rustfmt
    strategy:
      matrix:
        platform: [ubuntu-latest, blacksmith-staging, blacksmith]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt

      - run: cargo +nightly fmt -- --check
