name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  strategy:
      matrix:
        platform: [ubuntu-latest, blacksmith-staging, blacksmith]
  rust:
    name: Lint and Test
    runs-on: {{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy

      - uses: useblacksmith/rust-cache@v3

      - run: cargo build --all-features

      - run: cargo test

      - run: cargo clippy -- -D warnings

  rustfmt:
    name: Rustfmt
    runs-on: {{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt

      - run: cargo +nightly fmt -- --check
