name: Upload Binaries

on:
  push:
    tags:
      - "blobnet-v*.*.*"

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  upload:
    name: Upload binaries
    if: github.repository_owner == 'modal-labs'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - run: cargo build --release --bin blobnet

      - name: Install AWS CLI v2
        uses: unfor19/install-aws-cli-action@v1.0.3

      - name: Upload binary
        run: |
          aws s3 cp target/release/blobnet "s3://modal-artifacts/blobnet/blobnet-${GITHUB_REF#refs/tags/blobnet-v}"
